# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 21:47
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_page_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='condition_utilisation', editable=False, populate_from='title', unique_with=['created_on__month']),
            preserve_default=False,
        ),
    ]
