# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-01 07:56
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(default='test'),
            preserve_default=False,
        ),
    ]
