# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-08 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
