# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlive',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eventlive',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
