# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-24 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_auto_20181219_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name': 'Event Category', 'verbose_name_plural': 'Event Categorie(s)'},
        ),
        migrations.AlterModelOptions(
            name='eventlivecommentconf',
            options={'verbose_name': 'Event Live Comment Configuration', 'verbose_name_plural': 'Event Live Comment Configuration(s)'},
        ),
        migrations.AlterModelOptions(
            name='eventlivestreamconf',
            options={'verbose_name': 'Event Live Stream Configuration', 'verbose_name_plural': 'Event Live Stream Configuration(s)'},
        ),
    ]
