# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-07 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_auto_20190131_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlive',
            name='is_qa',
        ),
    ]
