# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-08 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_remove_eventlive_is_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventlive',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventlivestreamconf',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
