# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEvent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myeventlive',
            name='ip',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
