# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyEvent', '0003_auto_20190124_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpreorder',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventpreorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myeventlive',
            name='buyer_ip',
        ),
        migrations.DeleteModel(
            name='EventPreOrder',
        ),
    ]
