# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-21 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEvent', '0006_myeventlive_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='myeventlive',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
